apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: {{ .Release.Namespace }}
data:
  .env: |
    ACTUATOR_PORT=8081
    APPLICATION_PORT=8080
    ISSUER={{ .Values.application.vauthenticator.baseUrl }}
    ALLOWED_ROLE={{ .Values.application.allowedRole }}
    ALLOWED_ORIGIN={{ .Values.application.corsAllowedOrigins }}