apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "account-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      name: http
  selector:
    {{- include "account-api.selectorLabels" . | nindent 4 }}