services:
  account-api:
    container_name: account-api 
    build:
      context: ../
      dockerfile: Dockerfile
    ports:   
      - 6060:6060
      - 6061:6061
    volumes:
      - ../.env:/.env:ro

        
      