name: build Portal

on:
  push: { }
  workflow_dispatch: {}

jobs:
  build-i18n-api:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: portal/i18n-api
      services:
        localstack:
          image: localstack/localstack:3.2
          ports:
            - "4566-4599:4566-4599"
          env:
            SERVICES: s3
    steps:
      - name: checkout
        uses: actions/checkout@v6
      
      - name: Set up Golang
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1

      - name: Build i18n-api package
        run: |
          go build -o app .

      - name: Run tests
        env:
          CONFIG_FILE_LOCATION: test/application.yml
        run: |
          go test -tags test ./...