name: build Plan API

on:
  push: { }
  workflow_dispatch: {}

jobs:
  build-plan-api:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: plan/plan-api
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: checkout
        uses: actions/checkout@v6
      
      - name: Set up Golang
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1

      - name: Build plan-api package
        run: |
          go build -o app .

      - name: Run tests
        env:
          CONFIG_FILE_LOCATION: test/application.yml
        run: |
          go test -tags test ./...